export const USER_FETCH = "USER_FETCH";
export const USER_FETCH_PENDING = "USER_FETCH_PENDING";
export const USER_FETCH_FULFILLED = "USER_FETCH_FULFILLED";
export const USER_FETCH_REJECTED = "USER_FETCH_REJECTED";

export const USER_STATUS = "USER_STATUS";
export const USER_FETCH_BYID = "USER_FETCH_BYID";

export const USER_LOGOUT = "USER_LOGOUT";

export const SAVE_AUTH_DATA = "SAVE_AUTH_DATA";

export const STREAM_ADDED = "STREAM_ADDED";
export const STREAM_STATUS_CHANGE = "STREAM_STATUS_CHANGE";
export const STREAM_REMOVED = "STREAM_REMOVED";

export const CHAT_USER_ADDED = "CHAT_USER_ADDED";
export const CHAT_USER_REMOVED = "CHAT_USER_REMOVED";
export const CHAT_RECEIVED = "CHAT_RECEIVED";
export const CHAT_SENT = "CHAT_SENT";
export const POLL_ADD = "POLL_ADD";

export const USER_LIST_FETCH_FULFILLED = "USER_ROLES_FETCH_FULFILLED";
export const USER_LIST_FETCH_REJECTED = "USER_ROLES_FETCH_REJECTED";

export const CHAT_DISABLED = "CHAT_DISABLED";
export const FREE_ROAM_DISABLED = "FREE_ROAM_DISABLED";
export const TELEPORT_DISABLED = "TELEPORT_DISABLED";
export const SET_CURRENT_ZONE = "SET_CURRENT_ZONE";
export const HOST_TAKEOVER = "HOST_TAKEOVER";

export const SCREEN_SHARE = "SCREEN_SHARE";

export const HOST_ACTION_ADD = "HOST_ACTION_ADD";

export const WHITEBOARD_ADD = "WHITEBOARD_ADD";
